### ISSUE TITLE
for i in range(channels): - TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by sm3ulc** [rossengeorgiev/aprs-python#55] opened 2019-10-26 19:14 UTC
This packet:
APRS Packet: b'CA2JAT-7>SPP20W,WIDE1-1,WIDE2-1,qAR,CA2JAT-10:`bFll \x1c[/`1200bps_$'
Ends up in this:

Traceback (most recent call last):
  File "test2.py", line 102, in <module>
    AIS.consumer(callback, raw=True)
  File "/usr/local/lib/python3.7/site-packages/aprslib/inet.py", line 183, in consumer
    callback(line)
  File "test2.py", line 68, in callback
    parsed = aprslib.parse(packet)
  File "/usr/local/lib/python3.7/site-packages/aprslib/parsing/__init__.py", line 114, in parse
    _try_toparse_body(packet_type, body, parsed)
  File "/usr/local/lib/python3.7/site-packages/aprslib/parsing/__init__.py", line 186, in _try_toparse_body
    body, result = parse_mice(parsed['to'], body)
  File "/usr/local/lib/python3.7/site-packages/aprslib/parsing/mice.py", line 195, in parse_mice
    for i in range(channels):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by rossengeorgiev** [comment] 2019-10-26 19:18
Duplicate of #54. I've pushed a new release, just update.

**Closed by rossengeorgiev** 2019-10-26 19:18 UTC
